# Generated by Django 4.0.2 on 2022-04-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NapsackAdmin', '0001_initial'),
        ('Agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproducts',
            name='Categories_name',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='agentproducts',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NapsackAdmin.productscategories'),
        ),
        migrations.DeleteModel(
            name='AgentProductsCategories',
        ),
    ]
