# Generated by Django 4.0.2 on 2022-04-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0002_agentproducts_categories_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentordersproducts',
            old_name='customer_product_id',
            new_name='product_id',
        ),
    ]
