# Generated by Django 4.0.2 on 2022-04-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0003_rename_customer_product_id_agentordersproducts_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentorders',
            name='agent_order_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
