# Generated by Django 4.0.2 on 2022-04-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0004_alter_agentorders_agent_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentorders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agentorders',
            name='city_district_town',
        ),
        migrations.RemoveField(
            model_name='agentorders',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='agentorders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='agentorders',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='agentorders',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='agentorders',
            name='state',
        ),
        migrations.RemoveField(
            model_name='agentordersproducts',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agentordersproducts',
            name='city_district_town',
        ),
        migrations.RemoveField(
            model_name='agentordersproducts',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='agentordersproducts',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='agentordersproducts',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='agentordersproducts',
            name='state',
        ),
    ]
