# Generated by Django 4.0.2 on 2022-04-26 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0005_remove_agentorders_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentorders',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
