# Generated by Django 4.0.2 on 2022-04-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0006_alter_agentorders_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsusers',
            name='agent_verification',
            field=models.BooleanField(default=False),
        ),
    ]
