# Generated by Django 4.0.2 on 2022-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0007_agentsusers_agent_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsusers',
            name='image',
            field=models.ImageField(default='product.png', upload_to='agents'),
        ),
    ]
