# Generated by Django 4.0.2 on 2022-05-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0011_alter_agentsusers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentordersproducts',
            name='image',
            field=models.ImageField(default='customer_products.jpg', upload_to='images'),
        ),
    ]
