# Generated by Django 4.0.2 on 2022-04-26 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('pincode', models.PositiveIntegerField()),
                ('locality', models.TextField()),
                ('address', models.TextField()),
                ('city_district_town', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oder_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_id', models.CharField(max_length=200, unique=True)),
                ('status', models.TextField()),
                ('bill', models.CharField(max_length=100)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerUsers',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_verify', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProducts',
            fields=[
                ('customer_product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('Categorie', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('customerorders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorders')),
            ],
        ),
        migrations.AddField(
            model_name='customerorders',
            name='customerusername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerusers'),
        ),
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.UUIDField()),
                ('product_id', models.UUIDField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customerusername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerusers')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('pincode', models.PositiveIntegerField()),
                ('locality', models.TextField()),
                ('address', models.TextField()),
                ('city_district_town', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('customerusername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerusers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
