# Generated by Django 4.0.2 on 2022-04-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customerorders',
            name='city_district_town',
        ),
        migrations.RemoveField(
            model_name='customerorders',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='customerorders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customerorders',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customerorders',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='customerorders',
            name='state',
        ),
    ]
