# Generated by Django 4.0.2 on 2022-04-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_remove_customerorders_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='order_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
