# Generated by Django 4.0.2 on 2022-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_customerorders_latitude_customerorders_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='payment_mode',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='payment_id',
            field=models.CharField(max_length=200),
        ),
    ]
