# Generated by Django 4.0.2 on 2022-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_customerorders_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproducts',
            name='image',
            field=models.ImageField(default='customer_products.jpg', upload_to='customer_products/'),
        ),
    ]
