# Generated by Django 4.0.2 on 2022-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_customerproducts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproducts',
            name='image',
            field=models.ImageField(default='customer_products.jpg', upload_to='images/'),
        ),
    ]
