# Generated by Django 4.0.2 on 2022-04-27 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agents', '0006_alter_agentorders_delivery_date'),
        ('Customer', '0003_alter_customerorders_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerUsers',
            fields=[
                ('full_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('dealer_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DealertLocation',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Dealer.dealerusers')),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dealer_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DealerShopsVerifications',
            fields=[
                ('verification_id', models.UUIDField(primary_key=True, serialize=False)),
                ('verify_status', models.BooleanField(default=False)),
                ('agent_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agents.agentlocation')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dealer.dealerusers')),
            ],
        ),
        migrations.CreateModel(
            name='DealerOrders',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('oder_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.TextField()),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agents.agentorders')),
                ('customer_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customerorders')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dealer.dealerusers')),
            ],
        ),
    ]
