# Generated by Django 4.0.2 on 2022-04-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerorders',
            name='dealer_status',
            field=models.BooleanField(default=False),
        ),
    ]
