# Generated by Django 4.0.2 on 2022-04-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0003_alter_dealertlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerusers',
            name='dealer_verification',
            field=models.BooleanField(default=False),
        ),
    ]
