# Generated by Django 4.0.2 on 2022-04-29 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0004_dealerusers_dealer_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealershopsverifications',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
