# Generated by Django 4.0.2 on 2022-04-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0005_dealershopsverifications_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealershopsverifications',
            name='agent_user_id',
            field=models.UUIDField(default=None),
        ),
    ]
