# Generated by Django 4.0.2 on 2022-04-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0006_dealershopsverifications_agent_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealershopsverifications',
            name='agent_user_id',
        ),
    ]
