# Generated by Django 4.0.2 on 2022-04-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0008_alter_dealershopsverifications_verification_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealershopsverifications',
            old_name='data',
            new_name='date',
        ),
    ]
