# Generated by Django 4.0.2 on 2022-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0009_rename_data_dealershopsverifications_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerusers',
            name='image',
            field=models.ImageField(default='images/shop.jpeg', upload_to='dealer'),
        ),
    ]
